#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 25 10:40:13 2022

@author: nicolo
"""

import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import norm

def acc(r1, r2, m):
  return m*(r1-r2)/(norm(r1-r2)+0.01**2)**3

orbit1x = []
orbit2x = []
orbit1y = []
orbit2y = []

m = np.array([1.,1.], float)

x = np.zeros([2,2], float)
v = np.zeros([2,2], float)
a = np.zeros([2,2], float)

x[0,:] = [1.,-1.]
x[1,:] = [1.,-1.]

v[0,:] = [-0.5,0.5]
v[1,:] = [0.,0.]

ti = 0
tf = 300
h = 0.01

while ti<tf:
  orbit1x.append(x[0,0])
  orbit2x.append(x[1,0])
  orbit1y.append(x[0,1])
  orbit2y.append(x[1,1])
  for i in range(0, 2):
    x[i,:]+=v[i,:]*h
    for j in range(0,2):
      a[i,:]+=acc(x[i,:],x[j,:],m[j])
    v[i,:]+=(a[i,:])*h
  ti+=h

plt.plot(orbit1x, orbit1y)
plt.plot(orbit2x, orbit2y)
plt.show()